name: Deploy static site to Azure Web App - f1-cloud-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_46DEAA32496140DEAF322FAFD4E4E327 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FD49182CE1094DFEA81F9D29DA5F2C6D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7650FA12D97A4275AE218FE83DD52EC5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: f1-cloud-demo
          slot-name: Production
          package: .
